/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemperatureRouteImport } from './routes/temperature'
import { Route as SumRouteImport } from './routes/sum'
import { Route as ReverseRouteImport } from './routes/reverse'
import { Route as PersonRouteImport } from './routes/person'
import { Route as PalindromeRouteImport } from './routes/palindrome'
import { Route as FilterRouteImport } from './routes/filter'
import { Route as IndexRouteImport } from './routes/index'

const TemperatureRoute = TemperatureRouteImport.update({
  id: '/temperature',
  path: '/temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const SumRoute = SumRouteImport.update({
  id: '/sum',
  path: '/sum',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverseRoute = ReverseRouteImport.update({
  id: '/reverse',
  path: '/reverse',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonRoute = PersonRouteImport.update({
  id: '/person',
  path: '/person',
  getParentRoute: () => rootRouteImport,
} as any)
const PalindromeRoute = PalindromeRouteImport.update({
  id: '/palindrome',
  path: '/palindrome',
  getParentRoute: () => rootRouteImport,
} as any)
const FilterRoute = FilterRouteImport.update({
  id: '/filter',
  path: '/filter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filter': typeof FilterRoute
  '/palindrome': typeof PalindromeRoute
  '/person': typeof PersonRoute
  '/reverse': typeof ReverseRoute
  '/sum': typeof SumRoute
  '/temperature': typeof TemperatureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filter': typeof FilterRoute
  '/palindrome': typeof PalindromeRoute
  '/person': typeof PersonRoute
  '/reverse': typeof ReverseRoute
  '/sum': typeof SumRoute
  '/temperature': typeof TemperatureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/filter': typeof FilterRoute
  '/palindrome': typeof PalindromeRoute
  '/person': typeof PersonRoute
  '/reverse': typeof ReverseRoute
  '/sum': typeof SumRoute
  '/temperature': typeof TemperatureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/filter'
    | '/palindrome'
    | '/person'
    | '/reverse'
    | '/sum'
    | '/temperature'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/filter'
    | '/palindrome'
    | '/person'
    | '/reverse'
    | '/sum'
    | '/temperature'
  id:
    | '__root__'
    | '/'
    | '/filter'
    | '/palindrome'
    | '/person'
    | '/reverse'
    | '/sum'
    | '/temperature'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilterRoute: typeof FilterRoute
  PalindromeRoute: typeof PalindromeRoute
  PersonRoute: typeof PersonRoute
  ReverseRoute: typeof ReverseRoute
  SumRoute: typeof SumRoute
  TemperatureRoute: typeof TemperatureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temperature': {
      id: '/temperature'
      path: '/temperature'
      fullPath: '/temperature'
      preLoaderRoute: typeof TemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sum': {
      id: '/sum'
      path: '/sum'
      fullPath: '/sum'
      preLoaderRoute: typeof SumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverse': {
      id: '/reverse'
      path: '/reverse'
      fullPath: '/reverse'
      preLoaderRoute: typeof ReverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person': {
      id: '/person'
      path: '/person'
      fullPath: '/person'
      preLoaderRoute: typeof PersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palindrome': {
      id: '/palindrome'
      path: '/palindrome'
      fullPath: '/palindrome'
      preLoaderRoute: typeof PalindromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filter': {
      id: '/filter'
      path: '/filter'
      fullPath: '/filter'
      preLoaderRoute: typeof FilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilterRoute: FilterRoute,
  PalindromeRoute: PalindromeRoute,
  PersonRoute: PersonRoute,
  ReverseRoute: ReverseRoute,
  SumRoute: SumRoute,
  TemperatureRoute: TemperatureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
